### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by brodybits** [mschulkind/cordova-true-native-android#3]
Thank you for the nice work! Can you explicitly state a license for this version?

As a suggestion, an option to use the project under the Apache 2.0 license would be great since it would match the Android, Cordova, and Pixate Freestyle licenses. Also for the iOS version.

I am very interested in making both Android & iOS versions work with [Pixate Freestyle](http://www.freestyle.org/) and possibly expanding the native UI elements.

**Comment by brodybits** [comment]
Hi @mschulkind looking at the other issues I understand it will take significant work to get anything useful and suspect you may have moved on to some other work. My goal is to continue the work you have started and approach the capabilities of the AppGyver Supersonic UI in a fully open-source manner.

**Comment by mschulkind** [comment]
Hey,

I just added an MIT license to the android version. I think this should be good enough? I like how the MIT license has even fewer restrictions than the apache license.

Also, happy to try to answer any questions you have as you go along, although I may not have incredibly good answers. I wrote this stuff a good while ago now and a lot has changed with ios and android and I haven't kept up.

**Comment by brody2consult** [comment]
Thanks! I also like the idea of fewer restrictions. I have to go somewhere now and will explain my reason for requesting the Apache license option sometime later. And thanks for your offer to help answer my questions, suspect they will be coming..
